//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyExpenseTracker.EntityFrameWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyExpense
    {
        public int ExpenseId { get; set; }
        public Nullable<int> FamilyMemberId { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    
        public virtual FamilyMember FamilyMember { get; set; }
    }
}
