//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyExpenseTracker.EntityFrameWork.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FamilyExpenseTrackerDBConnectionString : DbContext
    {
        public FamilyExpenseTrackerDBConnectionString()
            : base("name=FamilyExpenseTrackerDBConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FamilyExpense> FamilyExpenses { get; set; }
        public virtual DbSet<FamilyMember> FamilyMembers { get; set; }
    }
}
